const REG_POINT = 'client-area/registration';
const PRIVATE_AREA_POINT = 'secure/rest';

export const API = {
    REG_POINT,
    REG: `/${REG_POINT}`,
    CALCULATOR_PRODUCTS: `/${REG_POINT}/actions/calculator-products`,
    SEND_SMS: `/${REG_POINT}/route/SEND_SMS`,
    CALCULATOR_CALCULATE: `/${REG_POINT}/actions/calculator-change-period-and-amount`,
    CALCULATOR_OFFER: `/${REG_POINT}/actions/calculator-offer`,
    CONFIRM_PHONE_NEW: `/${REG_POINT}/registration/action/CONFIRM_PHONE_NEW_BORROWER_SEND_SMS_WITH_MAX_COUNT`,
    CONFIRM_PHONE: `/${REG_POINT}/registration/action/CONFIRM_PHONE_SEND_SMS_WITH_MAX_COUNT`,
    CONFIRM_UPDATE_PHONE: `/${REG_POINT}/registration/action/CONFIRM_UPDATE_PHONE_SEND_SMS_MAX_COUNT`,
    FLOW_INFO: `/${REG_POINT}/registration/flow-info`,
    FINISH: `/${REG_POINT}/registration/action/FINISH_CREDIT`,
    CONFIRM: `/${REG_POINT}/registration/action/CONFIRM_CREDIT`,
    CURRENT_USER: `/${REG_POINT}/current-user`,
    LOCATIONS: `/${REG_POINT}/actions/locations/`,
    GET_ANALYTICS: `/${REG_POINT}/analytics/get-analytics`,
    UPDATE_VV_STATUS: `/${REG_POINT}/actions/update`,
    FINISH_FLOW: `/${REG_POINT}/actions/finish-flow`,
    UPLOAD_DOCUMENT: `/${REG_POINT}/route/UPLOAD`,
    FIND_PRODUCTS: `/${REG_POINT}/route/FIND_PRODUCTS`,
    OFFER: `/${REG_POINT}/route/OFFER`,
    SEND_IOVATION: `/${REG_POINT}/route/SEND_IOVATION`,
    USER_BEHAVIOR: '/es-stat-collector/api/3/store/',
};

export const PRIVATE_AREA_API = {
    PAGE: `/${PRIVATE_AREA_POINT}/private-area/auth-user/next-page`,
    GET_ANALYTICS: `/${PRIVATE_AREA_POINT}/analitics/get-analitics`,
    CONFIRM_USER: `/${PRIVATE_AREA_POINT}/authentication/confirmUser`,
    LOGIN_USER: `/${PRIVATE_AREA_POINT}/authentication/login`,
    LOGIN_USER_VIA_EMAIL: `/${PRIVATE_AREA_POINT}/authentication/login-password`,
    PASSWORD_RECOVERY: `/${PRIVATE_AREA_POINT}/password-recovery/sendInstruction`,
    LOGOUT: `/${PRIVATE_AREA_POINT}/authentication/logout`,
    LOAN_DETAIL: `/${PRIVATE_AREA_POINT}/loan-detail/info`,
    FEEDBACK_SUBJECTS: `/${PRIVATE_AREA_POINT}/private-office/quality-service/init`,
    SEND_FEEDBACK: `/${PRIVATE_AREA_POINT}/private-office/quality-service/send`,
    LOAN_DETAIL_LIST: `/${PRIVATE_AREA_POINT}/loan-detail/list`,
    LOAN_DETAIL_READ: `/${PRIVATE_AREA_POINT}/loan-detail/read`,
    LOAN_HISTORY: `/${PRIVATE_AREA_POINT}/privateoffice/loan-history?{}`,
    LOAN_HISTORY_DETAIL: `/${PRIVATE_AREA_POINT}/privateoffice/oldLoanDetails`,
    LOAN_HISTORY_DOWNLOAD: `/${PRIVATE_AREA_POINT}/privateoffice/download-offer`,
    LOAN_BONUS_PAY: `/${PRIVATE_AREA_POINT}/bonus/spend/debt`,
    GET_LAST_CARD: `/${PRIVATE_AREA_POINT}/private-office/cards/last`,
    PRODUCTS: `/${PRIVATE_AREA_POINT}/private-office/settings/all-products`,
    BONUS: `/${PRIVATE_AREA_POINT}/bonus/read`,
    LOAN_BONUS_HISTORY: `/${PRIVATE_AREA_POINT}/bonus/list`,
    LOAN_BONUS_LEVEL_UP: `/${PRIVATE_AREA_POINT}/bonus/spend/new-product`,
    PROLONGATION_INFO: `/${PRIVATE_AREA_POINT}/rollover/read`,
    UPDATE_PROLONGATION_INFO: `/${PRIVATE_AREA_POINT}/rollover/calculate`,
    PROLONGATION_CARD_PROVIDER: `/${PRIVATE_AREA_POINT}/payment/active-credit-card-provider`,
    PROLONGATION_IFRAME_URL_MYMOID: `/${PRIVATE_AREA_POINT}/mymoid/payment/init-payment-rollover`,
    PROLONGATION_IFRAME_URL_PAYLANDS: `/${PRIVATE_AREA_POINT}/paylands/init-payment-rollover`,
    PROLONGATION_PAY_INFO: `/${PRIVATE_AREA_POINT}/rollover/pay/read`,
    PROLONGATION_BONUS_PAY: `/${PRIVATE_AREA_POINT}/bonus/spend/rollover`,
    DOC_LIST: `/${PRIVATE_AREA_POINT}/profile/fileContent/read`,
    PA_UPLOAD_DOC: `/${PRIVATE_AREA_POINT}/registration/upload-documents/PRIVATE_AREA`,
    PAYMENT_SCHEDULE: `/${PRIVATE_AREA_POINT}/loan-detail/paymentSchedule`,
    RESTRUCTURING: `/${PRIVATE_AREA_POINT}/restructing/readState`,
    RESTRUCTURING_SCHEDULE: `/${PRIVATE_AREA_POINT}/restructing/readSchedule`,
    CURRENT_USER: `/${PRIVATE_AREA_POINT}/authentication/currentUser`,
    PRE_CREDIT_STATUS: `/${PRIVATE_AREA_POINT}/pre-credit/status`,
    PRE_ORDER_CANSEL: `/${PRIVATE_AREA_POINT}/privateoffice/newLoan`,
    PRE_ORDER_CONFIRM: `/${PRIVATE_AREA_POINT}/pre-credit/approve`,
    PA_FAQ_INFO: '/api.php',
    PA_LOAN_PAY_INFO: `/${PRIVATE_AREA_POINT}/loan/pay/read?payment=NEXT_PAYMENT&{}`,
    PA_LOAN_PAY_MYMOID: `/${PRIVATE_AREA_POINT}/mymoid/payment/init-payment`,
    PA_LOAN_PAY_PAYLANDS: `/${PRIVATE_AREA_POINT}/paylands/init-payment`,
    PROFILE: `/${PRIVATE_AREA_POINT}/profile/read`,
    PROFILE_PERSONAL: `/${PRIVATE_AREA_POINT}/profile/personalData/read`,
    PROFILE_ADDRESS: `/${PRIVATE_AREA_POINT}/profile/homeAddressData/read`,
    PROFILE_EMPLOYMENT: `/${PRIVATE_AREA_POINT}/profile/employmentData/read`,
    CHANGE_PASSWORD: `/${PRIVATE_AREA_POINT}/profile/changePass`,
};
